create database assingmentsdb
use assingmentsdb
CREATE TABLE Worker (

WORKER_ID INT PRIMARY KEY IDENTITY(1,1),

FIRST_NAME VARCHAR(25),

LAST_NAME VARCHAR(25),

SALARY INT,

JOINING_DATE DATETIME,

DEPARTMENT CHAR(25)

);

CREATE TABLE Bonus (

WORKER_REF_ID INT,

BONUS_AMOUNT INT,

BONUS_DATE DATETIME,

FOREIGN KEY (WORKER_REF_ID)

REFERENCES Worker(WORKER_ID)

ON DELETE CASCADE

);

CREATE TABLE Title (

WORKER_REF_ID INT,

WORKER_TITLE CHAR(25),

AFFECTED_FROM DATETIME,

FOREIGN KEY (WORKER_REF_ID)

REFERENCES Worker(WORKER_ID)

ON DELETE CASCADE

);
INSERT INTO Worker (FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT)
VALUES ('Monika', 'Arora', 100000, '2014-02-20 09:00:00', 'HR');

INSERT INTO Worker (FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT)
VALUES ('Niharika', 'Verma', 80000, '2014-06-11 09:00:00', 'Admin');

INSERT INTO Worker (FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT)
VALUES ('Vishal', 'Singhal', 300000, '2014-02-20 09:00:00', 'HR');

INSERT INTO Worker (FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT)
VALUES ('Amitabh', 'Singh', 500000, '2014-02-20 09:00:00', 'Admin');

INSERT INTO Worker (FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT)
VALUES ('Vivek', 'Bhati', 500000, '2014-06-11 09:00:00', 'Admin');

INSERT INTO Worker (FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT)
VALUES ('Vipul', 'Diwan', 200000, '2014-06-11 09:00:00', 'Account');

INSERT INTO Worker (FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT)
VALUES ('Satish', 'Kumar', 75000, '2014-01-20 09:00:00', 'Account');

INSERT INTO Worker (FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT)
VALUES ('Geetika', 'Chauhan', 90000, '2014-04-11 09:00:00', 'Admin');
INSERT INTO Bonus (WORKER_REF_ID, BONUS_AMOUNT, BONUS_DATE)
VALUES (1, 5000, '2016-02-20 00:00:00');

INSERT INTO Bonus (WORKER_REF_ID, BONUS_AMOUNT, BONUS_DATE)
VALUES (2, 3000, '2016-06-11 00:00:00');

INSERT INTO Bonus (WORKER_REF_ID, BONUS_AMOUNT, BONUS_DATE)
VALUES (3, 4000, '2016-02-20 00:00:00');

INSERT INTO Bonus (WORKER_REF_ID, BONUS_AMOUNT, BONUS_DATE)
VALUES (1, 4500, '2016-02-20 00:00:00');

INSERT INTO Bonus (WORKER_REF_ID, BONUS_AMOUNT, BONUS_DATE)
VALUES (2, 3500, '2016-06-11 00:00:00');
INSERT INTO Title (WORKER_REF_ID, WORKER_TITLE, AFFECTED_FROM)
VALUES (1, 'Manager', '2016-02-20 00:00:00');

INSERT INTO Title (WORKER_REF_ID, WORKER_TITLE, AFFECTED_FROM)
VALUES (2, 'Executive', '2016-06-11 00:00:00');

INSERT INTO Title (WORKER_REF_ID, WORKER_TITLE, AFFECTED_FROM)
VALUES (8, 'Executive', '2016-06-11 00:00:00');

INSERT INTO Title (WORKER_REF_ID, WORKER_TITLE, AFFECTED_FROM)
VALUES (5, 'Manager', '2016-06-11 00:00:00');

INSERT INTO Title (WORKER_REF_ID, WORKER_TITLE, AFFECTED_FROM)
VALUES (4, 'Asst. Manager', '2016-06-11 00:00:00');

INSERT INTO Title (WORKER_REF_ID, WORKER_TITLE, AFFECTED_FROM)
VALUES (7, 'Executive', '2016-06-11 00:00:00');

INSERT INTO Title (WORKER_REF_ID, WORKER_TITLE, AFFECTED_FROM)
VALUES (6, 'Lead', '2016-06-11 00:00:00');

INSERT INTO Title (WORKER_REF_ID, WORKER_TITLE, AFFECTED_FROM)
VALUES (3, 'Lead', '2016-06-11 00:00:00');
select * from Bonus
select * from Title
select * from Worker



/* Q1. Fetch FIRST_NAME as WORKER_NAME */
SELECT FIRST_NAME AS WORKER_NAME
FROM Worker;


/* Q2. Fetch FIRST_NAME in upper case */
SELECT UPPER(FIRST_NAME) AS FIRST_NAME
FROM Worker;


/* Q3. Fetch unique DEPARTMENT values */
SELECT DISTINCT DEPARTMENT
FROM Worker;


/* Q4. Print first three characters of FIRST_NAME */
SELECT SUBSTRING(FIRST_NAME, 1, 3) AS FIRST_3_CHAR
FROM Worker;


/* Q5. Find position of 'a' in 'Amitabh' */
SELECT CHARINDEX('a', FIRST_NAME) AS POSITION
FROM Worker
WHERE FIRST_NAME = 'Amitabh';


/* Q6. Remove right side spaces from FIRST_NAME */
SELECT RTRIM(FIRST_NAME) AS FIRST_NAME
FROM Worker;


/* Q7. Remove left side spaces from DEPARTMENT */
SELECT LTRIM(DEPARTMENT) AS DEPARTMENT
FROM Worker;


/* Q8. Unique DEPARTMENT and its length */
SELECT DISTINCT DEPARTMENT, LEN(DEPARTMENT) AS LENGTH
FROM Worker;


/* Q9. Replace 'a' with 'A' in FIRST_NAME */
SELECT REPLACE(FIRST_NAME, 'a', 'A') AS FIRST_NAME
FROM Worker;


/* Q10. Combine FIRST_NAME and LAST_NAME as COMPLETE_NAME */
SELECT FIRST_NAME + ' ' + LAST_NAME AS COMPLETE_NAME
FROM Worker;


/* Q11. Order Worker details by FIRST_NAME Ascending */
SELECT *
FROM Worker
ORDER BY FIRST_NAME ASC;


/* Q12. Order by FIRST_NAME Asc and DEPARTMENT Desc */
SELECT *
FROM Worker
ORDER BY FIRST_NAME ASC, DEPARTMENT DESC;


/* Q13. Workers with FIRST_NAME Vipul and Satish */
SELECT *
FROM Worker
WHERE FIRST_NAME IN ('Vipul', 'Satish');


/* Q14. Workers excluding Vipul and Satish */
SELECT *
FROM Worker
WHERE FIRST_NAME NOT IN ('Vipul', 'Satish');


/* Q15. Workers from Admin department */
SELECT *
FROM Worker
WHERE DEPARTMENT = 'Admin';


/* Q16. Workers whose FIRST_NAME contains 'a' */
SELECT *
FROM Worker
WHERE FIRST_NAME LIKE '%a%';


/* Q17. Workers whose FIRST_NAME ends with 'a' */
SELECT *
FROM Worker
WHERE FIRST_NAME LIKE '%a';


/* Q18. FIRST_NAME ends with 'h' and has six letters */
SELECT *
FROM Worker
WHERE FIRST_NAME LIKE '%h'
AND LEN(FIRST_NAME) = 6;


/* Q19. Workers with SALARY between 100000 and 500000 */
SELECT *
FROM Worker
WHERE SALARY BETWEEN 100000 AND 500000;


/* Q20. Workers who joined in Feb 2014 */
SELECT *
FROM Worker
WHERE MONTH(JOINING_DATE) = 2
AND YEAR(JOINING_DATE) = 2014;


/* Q21. Worker names with salary between 50000 and 100000 */
SELECT FIRST_NAME, SALARY
FROM Worker
WHERE SALARY BETWEEN 50000 AND 100000;


/* Q22. Count of workers in each department (Descending) */
SELECT DEPARTMENT, COUNT(*) AS TOTAL_WORKERS
FROM Worker
GROUP BY DEPARTMENT
ORDER BY TOTAL_WORKERS DESC;


/* Q23. Workers who are Managers */
SELECT W.*
FROM Worker W
JOIN Title T
ON W.WORKER_ID = T.WORKER_REF_ID
WHERE T.WORKER_TITLE = 'Manager';


/* Q24. Show current date and time */
SELECT GETDATE() AS CURRENT_DATE_TIME;


/* Q25. Show Top 10 records */
SELECT TOP 10 *
FROM Worker;
